# Generated by Django 2.1 on 2018-08-09 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('is_despesa', models.BooleanField(default=False)),
                ('is_receita', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data_despesa', models.DateField()),
                ('valor', models.FloatField()),
                ('pago', models.BooleanField(default=False)),
                ('observacao', models.CharField(max_length=300)),
                ('anexo', models.FileField(blank=True, upload_to='despesas/%d/%m/%Y/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.Categoria')),
                ('parcelas', models.ManyToManyField(related_name='_despesa_parcelas_+', to='despesas.Despesa')),
            ],
        ),
    ]
