# Generated by Django 2.1 on 2018-08-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='parcelado',
            field=models.BooleanField(default=False),
        ),
    ]
