# Generated by Django 2.1 on 2018-08-10 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_despesa_parcelado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('aceita_parcelamento', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('vencimento', models.DateField()),
                ('numero_parcela', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='despesa',
            old_name='pago',
            new_name='quitado',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='parcelado',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='parcelas',
        ),
        migrations.AddField(
            model_name='despesa',
            name='quantidade_parcela',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='despesa',
            name='valor_pago',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.Despesa'),
        ),
    ]
